// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDeu8lJxpnmCVsPtQd_LHwSE57pQOzE_o',
    appId: '1:793282396161:web:5caf8f4446e89b01c44000',
    messagingSenderId: '793282396161',
    projectId: 'flutterlogin-50112',
    authDomain: 'flutterlogin-50112.firebaseapp.com',
    storageBucket: 'flutterlogin-50112.firebasestorage.app',
    measurementId: 'G-PFE7LEBR9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlrjr0GtTESVLQn-_eXdP3TZ7ogwmWeo',
    appId: '1:793282396161:android:8a271840856ee84fc44000',
    messagingSenderId: '793282396161',
    projectId: 'flutterlogin-50112',
    storageBucket: 'flutterlogin-50112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTM3LWJjQVv5VTPxeUfnePiqMfr_NfRHs',
    appId: '1:793282396161:ios:86c178cdc24f0c3dc44000',
    messagingSenderId: '793282396161',
    projectId: 'flutterlogin-50112',
    storageBucket: 'flutterlogin-50112.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTM3LWJjQVv5VTPxeUfnePiqMfr_NfRHs',
    appId: '1:793282396161:ios:86c178cdc24f0c3dc44000',
    messagingSenderId: '793282396161',
    projectId: 'flutterlogin-50112',
    storageBucket: 'flutterlogin-50112.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDeu8lJxpnmCVsPtQd_LHwSE57pQOzE_o',
    appId: '1:793282396161:web:b31270d1601f6654c44000',
    messagingSenderId: '793282396161',
    projectId: 'flutterlogin-50112',
    authDomain: 'flutterlogin-50112.firebaseapp.com',
    storageBucket: 'flutterlogin-50112.firebasestorage.app',
    measurementId: 'G-YR8G61LS8M',
  );
}
